---
language: python
env:
  global:
  - secure: fn09X6nbswwkavXMJ0pff0W9yWgqoDXQt51KaQq0J3RSUd1z2yK3QA6Lp57IE13AAvzpb/rk2qH8Syy2sYr1m8tPIpbZjLKBkodxpiGaQOs/dGmDMmoUK7iViea9zuwEf5VrmbhLx4C9xeB0I75lm25yGlCFUTu6IeMka+QyrXd1OeTm99UseUnyqd1DXlUCneWSnb86bhpgyLwDGORw4le7fh7pzwMm1kwtnlHk5V0rOv7sQU15TnTfQIXW1uPtGBtupP4Xe3EoWUckeVv84isEN+X4+kD15VfMSX0KYTrdXb78vCFWy1OTbOEa3IOdsTu9QPGTsrfgvTZCUNy0HmU21P6ojA+A8QTYckhoG5FiLu25FASAcqqsyl7tey7fgQyWBHsZpcuLN8vNEdZ6jKobm/iUZxgS4Yb/AqMSlPGOHhG/MGJ+WCsQW6u5UaOn8N2r+ZNINxsp7wVlzkyXjz6PR3DH/u3SbMfGfUN6efxmF9ATSw/mlOakno35ZA8GRnaa1q6y1Wl4/kSL9QbSE9lz722LHvtfEOb8DvHGBd/5tUXK8Y6Xb5m8roYLY/DEOz2raYR1NNbeKfW8WHfjebh0VmE+3eL2QY3ZxBmQDdHezLYqRbsQQQyI9wAxJQQ0/npLYGk4n8IuyLCGcohmVlhDEWRGrfqGwUI7KPkK81U=
  - secure: UU5RZZ4EbzREBFW9JMstjzK79pL0ytSvth/uEQgcr5B5a5BSgnwcpR0jWinuuZPFmvk/L3bZvLqXwJO1Hq34LeJ/XoDPdWV3NRR+sCyIRhVobQgL9kWn3cBERWRunB48nR0wAEg8sn2cmCBjoP14/ELlp0Xf3fRgwWywCbJVad1OvydzyQtVj0Jxkgc/PB037IlKRHO+J5UQtFlbr3JAurqymxrzqslNweFFxbfu/W+oEzSKZJ611ITlaBPMVM1+y051qUvjikADl0pxDTP9lWHF1dePHkAVTGFOztQw+xB0BGoCD1GU6pOzQGDD4Q40FhL85o6YxRnSLUGPp5bqrz+h0LrNPQRYQlWWdBEazf6HS1mkBNgGdLw1obuMqXkzEXE8IXRp+Z3GsE3hnSqbbFeA7ToUrbWT5y+HZqNdHyU6T66zOk8bzxUV54W5sbJEv1jQcNDCJ3l5aoCbHCWXPDXx6Vap/5HZM835IF5NCEQWkx0ik5TWTubGb6o1XzFp5r4Vpj/Uc4S9nR68D8Kpbys4A0clQnbofgwp76B36BpuBWOmxxjex0Yz8YPdbkZ6turKtCybAHUN9ps0pG+CAXddToDdJxiBRlMgZp83Vzye5X/eItVCOMVj4djabxFs//hqFZLB1qKvcMiCl0BFd3h8fPWB50tu8edAVmoTBso=
  - AWS_DEFAULT_REGION=us-east-1
python:
- '3.6'
install:
- pip install yamllint
- pip install awscli
script:
- yamllint .
- find . -type f -name '*.y?ml' | while read file; do set -ex && aws s3 cp "$file"
  "s3://immdevops/aws-cf-templates/$TRAVIS_COMMIT/$file" && aws cloudformation validate-template
  --template-url "https://s3.amazonaws.com/immdevops/aws-cf-templates/$TRAVIS_COMMIT/$file"
  > /dev/null; done
notifications:
  hipchat:
    rooms:
      secure: T3bA32pQGoi80qhIYx2wgxCjvzrNbf47Ckw/292V3IjO3UZzINWqpDaWo/bKI3PX8HykDf7SPAPuTbbi8/qwR+cmhujegVUxWJ2K9CYzwvpXKGEkGtEyj85jpYPm/+HAS6ZykZ/EJuRWx//Jq3Z/pTMpkQELUgi65Sbm4fMTmXJuB31zTB3ZpCuqnLa55I4OJexp1Ox+kzVLOC4Vt2Fkty/bA5P1f4Wur5WKGo2LJ5wVcHvRHnhjwSVyqUx7Yb2qrz4ntZOpcJRN70ooGxbfH67d3KmUbdyPw1gOoVw527nOUeAxWBkmWsMpNKpN4PjOLwUQU2QVipQwxBCNSPpNwmdaD3FAB5l+WDZIx2WjZqQ9LSFeOhdAJ8lCVv9dLgsXUEMO7vMMU2ZAxMJv7l+DxUlD1Kar3Q9TVywwo2uMA2+EfylFBm1YjozW1FFnbIzc4gxswrXMTyUUTteLdktlJGNl1NwV8irt0/3MKIq0Vvc1MPjF0MPgVukBv5uDkv1cHcUWNmlZm1KOlPXK+sqAoPPq1/uVM+4dHltixCupRlpv4rqrbgKpN6SD2dvCtJcvOVSMfG/5qwG8U1buXD91TYLVNgATxQUVZ3+o0oywB46rHjQyYBTsBzVnweXeQxJ1c+UuMyiHpEUsiSjq1KCJz3nxbEuPL3XdWzgiJ77L7Hg=
