---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fargate: service that runs on a Fargate cluster based on fargate/cluster.yaml and uses the cluster ALB, a cloudonaut.io template'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentVPCStack
      - ParentClusterStack
      - ParentAlertStack
      - ParentZoneStack
      - ParentClientStack1
      - ParentClientStack2
      - ParentClientStack3
    - Label:
        default: 'Load Balancer Parameters'
      Parameters:
      - LoadBalancerPriority
      - LoadBalancerHostPattern
      - LoadBalancerPathPattern
      - LoadBalancerHttps
      - LoadBalancerDeregistrationDelay
    - Label:
        default: 'Task Parameters'
      Parameters:
      - TaskPolicies
      - ProxyImage
      - ProxyCommand
      - ProxyPort
      - ProxyEnvironment1Key
      - ProxyEnvironment1Value
      - ProxyEnvironment2Key
      - ProxyEnvironment2Value
      - ProxyEnvironment3Key
      - ProxyEnvironment3Value
      - AppImage
      - AppCommand
      - AppPort
      - AppEnvironment1Key
      - AppEnvironment1Value
      - AppEnvironment2Key
      - AppEnvironment2Value
      - AppEnvironment3Key
      - AppEnvironment3Value
      - SidecarImage
      - SidecarCommand
      - SidecarPort
      - SidecarEnvironment1Key
      - SidecarEnvironment1Value
      - SidecarEnvironment2Key
      - SidecarEnvironment2Value
      - SidecarEnvironment3Key
      - SidecarEnvironment3Value
    - Label:
        default: 'Service Parameters'
      Parameters:
      - SubDomainNameWithDot
      - Cpu
      - Memory
      - SubnetsReach
      - AutoScaling
      - DesiredCount
      - MaxCapacity
      - MinCapacity
      - HealthCheckGracePeriod
      - LogsRetentionInDays
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  ParentClusterStack:
    Description: 'Stack name of parent Cluster stack based on fargate/cluster.yaml template.'
    Type: String
  ParentAlertStack:
    Description: 'Optional but recommended stack name of parent alert stack based on operations/alert.yaml template.'
    Type: String
    Default: ''
  ParentZoneStack:
    Description: 'Optional stack name of parent zone stack based on vpc/zone-*.yaml template.'
    Type: String
    Default: ''
  ParentClientStack1:
    Description: 'Optional stack name of parent Client Security Group stack based on state/client-sg.yaml template to allow network access from the service to whatever uses the client security group.'
    Type: String
    Default: ''
  ParentClientStack2:
    Description: 'Optional stack name of parent Client Security Group stack based on state/client-sg.yaml template to allow network access from the service to whatever uses the client security group.'
    Type: String
    Default: ''
  ParentClientStack3:
    Description: 'Optional stack name of parent Client Security Group stack based on state/client-sg.yaml template to allow network access from the service to whatever uses the client security group.'
    Type: String
    Default: ''
  LoadBalancerPriority:
    Description: 'The priority for the rule. Elastic Load Balancing evaluates rules in priority order, from the lowest value to the highest value. If a request satisfies a rule, Elastic Load Balancing ignores all subsequent rules. A target group can have only one rule with a given priority.'
    Type: Number
    Default: 1
    ConstraintDescription: 'Must be in the range [1-99999]'
    MinValue: 1
    MaxValue: 99999
  LoadBalancerHostPattern:
    Description: 'Optional host pattern. Specify LoadBalancerPathPattern and/or LoadBalancerHostPattern.'
    Type: String
    Default: ''
    ConstraintDescription: 'Must not be longer than 255'
    MaxLength: 255
  LoadBalancerPathPattern:
    Description: 'Optional path pattern. Specify LoadBalancerPathPattern and/or LoadBalancerHostPattern.'
    Type: String
    Default: '/*'
    ConstraintDescription: 'Must not be longer than 255'
    MaxLength: 255
  LoadBalancerHttps:
    Description: 'If the cluster supports HTTPS (LoadBalancerCertificateArn is set) you can enable HTTPS for the service'
    Type: String
    Default: false
    AllowedValues:
    - true
    - false
  LoadBalancerDeregistrationDelay:
    Description: 'The amount time (in seconds) to wait before changing the state of a deregistering target from draining to unused.'
    Type: Number
    Default: 60
    ConstraintDescription: 'Must be in the range [0-3600]'
    MinValue: 0
    MaxValue: 3600
  TaskPolicies:
    Description: 'Comma-delimited list of IAM managed policy ARNs to attach to the task IAM role'
    Type: String
    Default: ''
  ProxyImage:
    Description: 'Optional Docker image to use for the proxy container. You can use images in the Docker Hub registry or specify other repositories (repository-url/image:tag).'
    Type: String
    Default: ''
  ProxyCommand:
    Description: 'Optional command used when starting the proxy container.'
    Type: String
    Default: ''
  ProxyPort:
    Description: 'The port exposed by the proxy container that receives traffic from the load balancer (ProxyPort <> AppPort <> SidecarPort; ignored if ProxyImage is not set).'
    Type: Number
    Default: 8000
    MinValue: 1
    MaxValue: 49150
  ProxyEnvironment1Key:
    Description: 'Optional environment variable 1 key for proxy container.'
    Type: String
    Default: ''
  ProxyEnvironment1Value:
    Description: 'Optional environment variable 1 value for proxy container.'
    Type: String
    Default: ''
  ProxyEnvironment2Key:
    Description: 'Optional environment variable 2 key for proxy container.'
    Type: String
    Default: ''
  ProxyEnvironment2Value:
    Description: 'Optional environment variable 2 value for proxy container.'
    Type: String
    Default: ''
  ProxyEnvironment3Key:
    Description: 'Optional environment variable 3 key for proxy container.'
    Type: String
    Default: ''
  ProxyEnvironment3Value:
    Description: 'Optional environment variable 3 value for proxy container.'
    Type: String
    Default: ''
  AppImage:
    Description: 'The Docker image to use for the app container. You can use images in the Docker Hub registry or specify other repositories (repository-url/image:tag).'
    Type: String
    Default: 'widdix/hello:v1'
  AppCommand:
    Description: 'Optional commands (comma-delimited) used when starting the app container.'
    Type: String
    Default: ''
  AppPort:
    Description: 'The port exposed by the app container that receives traffic from the load balancer or the proxy container (AppPort <> ProxyPort <> SidecarPort).'
    Type: Number
    Default: 80
    MinValue: 1
    MaxValue: 49150
  AppEnvironment1Key:
    Description: 'Optional environment variable 1 key for app container.'
    Type: String
    Default: ''
  AppEnvironment1Value:
    Description: 'Optional environment variable 1 value for app container.'
    Type: String
    Default: ''
  AppEnvironment2Key:
    Description: 'Optional environment variable 2 key for app container.'
    Type: String
    Default: ''
  AppEnvironment2Value:
    Description: 'Optional environment variable 2 value for app container.'
    Type: String
    Default: ''
  AppEnvironment3Key:
    Description: 'Optional environment variable 3 key for app container.'
    Type: String
    Default: ''
  AppEnvironment3Value:
    Description: 'Optional environment variable 3 value for app container.'
    Type: String
    Default: ''
  SidecarImage:
    Description: 'Optional Docker image to use for the sidecar container. You can use images in the Docker Hub registry or specify other repositories (repository-url/image:tag).'
    Type: String
    Default: ''
  SidecarCommand:
    Description: 'Optional command used when starting the sidecar container.'
    Type: String
    Default: ''
  SidecarPort:
    Description: 'The port exposed by the sidecar container reachable from the app container on host localhost (SidecarPort <> ProxyPort <> AppPort).'
    Type: Number
    Default: 9000
    MinValue: 1
    MaxValue: 49150
  SidecarEnvironment1Key:
    Description: 'Optional environment variable 1 key for sidecar container.'
    Type: String
    Default: ''
  SidecarEnvironment1Value:
    Description: 'Optional environment variable 1 value for sidecar container.'
    Type: String
    Default: ''
  SidecarEnvironment2Key:
    Description: 'Optional environment variable 2 key for sidecar container.'
    Type: String
    Default: ''
  SidecarEnvironment2Value:
    Description: 'Optional environment variable 2 value for sidecar container.'
    Type: String
    Default: ''
  SidecarEnvironment3Key:
    Description: 'Optional environment variable 3 key for sidecar container.'
    Type: String
    Default: ''
  SidecarEnvironment3Value:
    Description: 'Optional environment variable 3 value for sidecar container.'
    Type: String
    Default: ''
  SubDomainNameWithDot:
    Description: 'Name that is used to create the DNS entry with trailing dot, e.g. ยง{SubDomainNameWithDot}ยง{HostedZoneName}. Leave blank for naked (or apex and bare) domain. Requires ParentZoneStack parameter!'
    Type: String
    Default: ''
  Cpu:
    Description: 'The minimum number of vCPUs to reserve for the container.'
    Type: String
    Default: '0.25'
    AllowedValues: ['0.25', '0.5', '1', '2', '4']
  Memory:
    Description: 'The amount (in GB) of memory used by the task.'
    Type: String
    Default: '0.5'
    AllowedValues: ['0.5', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
  DesiredCount:
    Description: 'The number of simultaneous tasks, that you want to run on the cluster.'
    Type: Number
    Default: 2
    ConstraintDescription: 'Must be >= 1'
    MinValue: 1
  MaxCapacity:
    Description: 'The maximum number of simultaneous tasks, that you want to run on the cluster.'
    Type: Number
    Default: 4
    ConstraintDescription: 'Must be >= 1'
    MinValue: 1
  MinCapacity:
    Description: 'The minimum number of simultaneous tasks, that you want to run on the cluster.'
    Type: Number
    Default: 2
    ConstraintDescription: 'Must be >= 1'
    MinValue: 1
  LogsRetentionInDays:
    Description: 'Specifies the number of days you want to retain log events in the specified log group.'
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  SubnetsReach:
    Description: 'Should the service have direct access to the Internet or do you prefer private subnets with NAT?'
    Type: String
    Default: Public
    AllowedValues:
    - Public
    - Private
  AutoScaling:
    Description: 'Scale number of tasks based on CPU load?'
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
  HealthCheckGracePeriod:
    Description: 'The period of time, in seconds, that the Amazon ECS service scheduler ignores unhealthy Elastic Load Balancing target health checks after a task has first started.'
    Type: Number
    Default: 60
    MinValue: 0
    MaxValue: 1800
Conditions:
  HasLoadBalancerHttps: !Equals [!Ref LoadBalancerHttps, 'true']
  HasLoadBalancerPathPattern: !Not [!Equals [!Ref LoadBalancerPathPattern, '']]
  HasLoadBalancerHostPattern: !Not [!Equals [!Ref LoadBalancerHostPattern, '']]
  HasAlertTopic: !Not [!Equals [!Ref ParentAlertStack, '']]
  HasZone: !Not [!Equals [!Ref ParentZoneStack, '']]
  HasProxyImage: !Not [!Equals [!Ref ProxyImage, '']]
Resources:
  RecordSet:
    Condition: HasZone
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        HostedZoneId: {'Fn::ImportValue': !Sub '${ParentClusterStack}-CanonicalHostedZoneID'}
        DNSName: {'Fn::ImportValue': !Sub '${ParentClusterStack}-DNSName'}
      HostedZoneId: {'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneId'}
      Name: !Sub
      - '${SubDomainNameWithDot}${HostedZoneName}'
      - SubDomainNameWithDot: !Ref SubDomainNameWithDot
        HostedZoneName: {'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneName'}
      Type: A
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: '/'
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-299'
      Port: 8080 # overriden when containers are attached
      Protocol: HTTP
      TargetType: ip
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: !Ref LoadBalancerDeregistrationDelay
      VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}
  HTTPCodeTarget5XXTooHighAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer receives 5XX HTTP status codes from targets'
      Namespace: 'AWS/ApplicationELB'
      MetricName: HTTPCode_Target_5XX_Count
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Dimensions:
      - Name: LoadBalancer
        Value: {'Fn::ImportValue': !Sub '${ParentClusterStack}-LoadBalancerFullName'}
      - Name: TargetGroup
        Value: !GetAtt TargetGroup.TargetGroupFullName
      TreatMissingData: notBreaching
  TargetConnectionErrorCountTooHighAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Application load balancer could not connect to targets'
      Namespace: 'AWS/ApplicationELB'
      MetricName: TargetConnectionErrorCount
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0
      AlarmActions:
      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Dimensions:
      - Name: LoadBalancer
        Value: {'Fn::ImportValue': !Sub '${ParentClusterStack}-LoadBalancerFullName'}
      - Name: TargetGroup
        Value: !GetAtt TargetGroup.TargetGroupFullName
      TreatMissingData: notBreaching
  LoadBalancerListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref TargetGroup
      Conditions: !If
      - HasLoadBalancerPathPattern
      - !If
        - HasLoadBalancerHostPattern
        - - Field: host-header
            Values:
            - !Ref LoadBalancerHostPattern
          - Field: path-pattern
            Values:
            - !Sub '${LoadBalancerPathPattern}'
        - - Field: path-pattern
            Values:
            - !Sub '${LoadBalancerPathPattern}'
      - !If
        - HasLoadBalancerHostPattern
        - - Field: host-header
            Values:
            - !Ref LoadBalancerHostPattern
        - [] # neither LoadBalancerHostPattern nor LoadBalancerPathPattern specified
      ListenerArn: !If [HasLoadBalancerHttps, {'Fn::ImportValue': !Sub '${ParentClusterStack}-HttpsListener'}, {'Fn::ImportValue': !Sub '${ParentClusterStack}-HttpListener'}]
      Priority: !Ref LoadBalancerPriority
  ServiceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub '${AWS::StackName}-service'
      VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}
      SecurityGroupIngress:
      - SourceSecurityGroupId: {'Fn::ImportValue': !Sub '${ParentClusterStack}-LoadBalancerSecurityGroup'}
        FromPort: !If [HasProxyImage, !Ref ProxyPort, !Ref AppPort]
        ToPort: !If [HasProxyImage, !Ref ProxyPort, !Ref AppPort]
        IpProtocol: tcp
  Service:
    DependsOn: LoadBalancerListenerRule
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        LoadBalancerTargetGroup: !Ref TargetGroup
        ServiceSecurityGroup: !Ref ServiceSecurityGroup
        ParentVPCStack: !Ref ParentVPCStack
        ParentClusterStack: !Ref ParentClusterStack
        ParentAlertStack: !Ref ParentAlertStack
        ParentClientStack1: !Ref ParentClientStack1
        ParentClientStack2: !Ref ParentClientStack2
        ParentClientStack3: !Ref ParentClientStack3
        TaskPolicies: !Ref TaskPolicies
        ProxyImage: !Ref ProxyImage
        ProxyCommand: !Ref ProxyCommand
        ProxyPort: !Ref ProxyPort
        ProxyEnvironment1Key: !Ref ProxyEnvironment1Key
        ProxyEnvironment1Value: !Ref ProxyEnvironment1Value
        ProxyEnvironment2Key: !Ref ProxyEnvironment2Key
        ProxyEnvironment2Value: !Ref ProxyEnvironment2Value
        ProxyEnvironment3Key: !Ref ProxyEnvironment3Key
        ProxyEnvironment3Value: !Ref ProxyEnvironment3Value
        AppImage: !Ref AppImage
        AppCommand: !Ref AppCommand
        AppPort: !Ref AppPort
        AppEnvironment1Key: !Ref AppEnvironment1Key
        AppEnvironment1Value: !Ref AppEnvironment1Value
        AppEnvironment2Key: !Ref AppEnvironment2Key
        AppEnvironment2Value: !Ref AppEnvironment2Value
        AppEnvironment3Key: !Ref AppEnvironment3Key
        AppEnvironment3Value: !Ref AppEnvironment3Value
        SidecarImage: !Ref SidecarImage
        SidecarCommand: !Ref SidecarCommand
        SidecarPort: !Ref SidecarPort
        SidecarEnvironment1Key: !Ref SidecarEnvironment1Key
        SidecarEnvironment1Value: !Ref SidecarEnvironment1Value
        SidecarEnvironment2Key: !Ref SidecarEnvironment2Key
        SidecarEnvironment2Value: !Ref SidecarEnvironment2Value
        SidecarEnvironment3Key: !Ref SidecarEnvironment3Key
        SidecarEnvironment3Value: !Ref SidecarEnvironment3Value
        Cpu: !Ref Cpu
        Memory: !Ref Memory
        SubnetsReach: !Ref SubnetsReach
        AutoScaling: !Ref AutoScaling
        DesiredCount: !Ref DesiredCount
        MaxCapacity: !Ref MaxCapacity
        MinCapacity: !Ref MinCapacity
        HealthCheckGracePeriod: !Ref HealthCheckGracePeriod
        LogsRetentionInDays: !Ref LogsRetentionInDays
      TemplateURL: './aws-cf-templates/fargate/service-cloudmap.yaml'
Outputs:
  TemplateID:
    Description: 'cloudonaut.io template id.'
    Value: 'fargate/service-cluster-alb'
  TemplateVersion:
    Description: 'cloudonaut.io template version.'
    Value: '__VERSION__'
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
